//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngWebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mastery
    {
        public int MasteryID { get; set; }
        public int UsersID { get; set; }
        public int QuestionsID { get; set; }
        public int TotalTries { get; set; }
        public int CorrectTries { get; set; }
        public string DifficultyLevel { get; set; }
        public double DifficultyPercentage { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
